### ISSUE TITLE
About the name of the npm library

### ISSUE THREAD

**Issue by GermanJablo** [treedoc/treedoc_ts#14]
Hi Jianwu,

I hope this message finds you well.

My name is Germán, and I am currently working on a new CRDT (Conflict-Free Replicated Data Type) library, similar to yjs. I'm interested in naming my project "treedoc" because it fits perfectly with its nature.

I noticed that you are the current owner of the "treedoc" package on npm. Since I only see your activity in this repository, I was wondering if you would be willing to free up the "treedoc" name on npm so that I could use it for my CRDT library. This would greatly help in aligning the project's identity with its intended purpose and making it easily discoverable for developers interested in CRDTs.

I would greatly appreciate your kindness and understanding in this matter. Thank you very much for considering my request. I look forward to your response.

Best,
Germán

**Comment by jianwu** [comment]
Sorry, treedoc is my active project. I'm also the owner of the domain name `treedoc.org` with an active application used by many people. It will be hard for me to free up this name that will break the dependencies.
